version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.1.0

workflows:
  build_and_push_image:
    jobs:
      - build_and_push_image:
            steps:
              - checkout
              - aws-ecr/build-and-push-image:
                context: aws-dev
                create-repo: true
                dockerfile: Dockerfile
                path: .
                repo: circleci-ecr-app-demo
                tag: "$CIRCLE_SHA1"
    
